In [16]:
import pandas as pd
import numpy as np
import yfinance as yf

In [17]:
tickers = [
    "BESI.AS",
    "ALBIO.PA",
    "ENGI.PA",
    "MAU.PA",
    "ALRIB.PA",
    "STMPA.PA",
    "HO.PA",
    "VLA.PA",
    "LQQ.PA",
    "EXA1.AS",
    "ETL.PA",
]

In [18]:
weights = np.array([
    0.0664653,  # BESI
    0.0166811,  # Biosynex
    0.0857736,  # Engie
    0.0352324,  # Maurel & Prom
    0.0288497,  # Riber
    0.0681581,  # STMicro
    0.0887683,  # Thales
    0.0151301,  # Valneva
    0.228948,  # LQQ
    0.339815,  # EXA1
    0.0243977, # Eutelsat
])

In [19]:
prices = yf.download(
    tickers,
    start="2021-12-24",
    end="2026-09-15",
    auto_adjust=True
)["Close"]

[*********************100%***********************]  11 of 11 completed

In [20]:
prices = prices.drop(pd.Timestamp("2026-09-07"))
prices = prices.drop(pd.Timestamp("2025-10-24"))

In [21]:
#print(prices.columns)
print(weights.sum())
print(prices.isna().sum())

0.9982193
Ticker
ALBIO.PA    0
ALRIB.PA    0
BESI.AS     0
ENGI.PA     0
ETL.PA      0
EXA1.AS     0
HO.PA       0
LQQ.PA      0
MAU.PA      0
STMPA.PA    0
VLA.PA      0
dtype: int64

In [22]:
 prices[prices.isna().any(axis=1)]

Empty DataFrame
Columns: [ALBIO.PA, ALRIB.PA, BESI.AS, ENGI.PA, ETL.PA, EXA1.AS, HO.PA, LQQ.PA, MAU.PA, STMPA.PA, VLA.PA]
Index: []

In [23]:
returns = prices.pct_change().dropna()
cov_matrix = returns.cov()
cov_matrix

portfolio_variance = weights.T @ cov_matrix @ weights
portfolio_variance

portfolio_volatility = np.sqrt(portfolio_variance) 
portfolio_volatility

np.float64(0.015316733510138783)

In [24]:
annual_portfolio_volatility = portfolio_volatility * np.sqrt(252)
print(f"{annual_portfolio_volatility * 100} %")

24.31456065940598 %

In [25]:
returns = prices.pct_change(fill_method=None).dropna()
returns.head()

Ticker,ALBIO.PA,ALRIB.PA,BESI.AS,ENGI.PA,ETL.PA,EXA1.AS,HO.PA,LQQ.PA,MAU.PA,STMPA.PA,VLA.PA
Date,,,,,,,,,,,
2021-12-27,0.104273,0.004395,-0.002139,0.004041,0.000465,0.006534,0.007787,0.021554,0.000000,0.009651,0.047657
2021-12-28,-0.038700,-0.015317,0.010185,0.015789,-0.000930,0.006607,0.006395,0.001871,0.031603,0.002276,-0.025777
2021-12-29,-0.023349,-0.007778,-0.021756,0.001829,-0.000466,-0.001385,-0.004766,-0.011827,-0.019694,-0.005563,-0.029572
2021-12-30,0.083265,-0.016797,0.013019,-0.005780,-0.000466,0.000494,0.001596,0.013858,0.000000,-0.001256,-0.010425
2021-12-31,0.001522,-0.003417,0.004284,-0.004437,0.000466,-0.001747,-0.006640,-0.013876,0.017857,-0.008459,-0.007293

In [26]:
cov_matrix

Ticker,ALBIO.PA,ALRIB.PA,BESI.AS,ENGI.PA,ETL.PA,EXA1.AS,HO.PA,LQQ.PA,MAU.PA,STMPA.PA,VLA.PA
Ticker,,,,,,,,,,,
ALBIO.PA,0.002321,0.000037,0.000104,0.000058,0.000136,0.000049,0.000025,0.000111,0.000019,0.000027,0.000205
ALRIB.PA,0.000037,0.001079,0.000197,0.000038,0.000142,0.000107,0.000050,0.000207,0.000042,0.000200,0.000140
BESI.AS,0.000104,0.000197,0.000964,0.000052,0.000118,0.000157,0.000019,0.000456,0.000108,0.000474,0.000191
ENGI.PA,0.000058,0.000038,0.000052,0.000190,0.000019,0.000082,0.000030,0.000046,0.000021,0.000057,0.000063
ETL.PA,0.000136,0.000142,0.000118,0.000019,0.003638,0.000103,0.000235,0.000050,-0.000007,0.000091,0.000124
EXA1.AS,0.000049,0.000107,0.000157,0.000082,0.000103,0.000250,0.000036,0.000177,0.000041,0.000167,0.000176
HO.PA,0.000025,0.000050,0.000019,0.000030,0.000235,0.000036,0.000335,0.000056,0.000077,0.000009,0.000020
LQQ.PA,0.000111,0.000207,0.000456,0.000046,0.000050,0.000177,0.000056,0.000658,0.000094,0.000386,0.000277
MAU.PA,0.000019,0.000042,0.000108,0.000021,-0.000007,0.000041,0.000077,0.000094,0.000758,0.000068,0.000115
STMPA.PA,0.000027,0.000200,0.000474,0.000057,0.000091,0.000167,0.000009,0.000386,0.000068,0.000714,0.000190
VLA.PA,0.000205,0.000140,0.000191,0.000063,0.000124,0.000176,0.000020,0.000277,0.000115,0.000190,0.001846

In [27]:
print(len(tickers))
print(len(weights))
print(weights.sum())

11
11
0.9982193

In [28]:
portfolio_returns = returns @ weights
portfolio_returns.head()

Date
2021-12-27    0.012881
2021-12-28    0.007001
2021-12-29   -0.011314
2021-12-30    0.005858
2021-12-31    0.000386
dtype: float64

In [29]:

portfolio_volatility_direct = portfolio_returns.std()
portfolio_volatility_direct

np.float64(0.015316733510138784)

In [30]:
np.sqrt(portfolio_variance)
# portfolio_variance et portfolio_volatility_direct sont identiques, parfait!

np.float64(0.015316733510138783)

In [31]:
candidate = yf.download(
    "SAN.PA",
    start="2021-12-24",
    end="2026-09-15",
    auto_adjust = True
)["Close"]
candidate.head()

[*********************100%***********************]  1 of 1 completed

Ticker         SAN.PA
Date
2021-12-24  70.911003
2021-12-27  71.484032
2021-12-28  71.734230
2021-12-29  71.669670
2021-12-30  71.936005

In [51]:
candidate_returns = candidate.pct_change(fill_method=None).dropna()
candidate_returns.head()

Ticker        SAN.PA
Date
2021-12-27  0.008081
2021-12-28  0.003500
2021-12-29 -0.000900
2021-12-30  0.003716
2021-12-31 -0.006171

In [52]:
comparison = pd.concat(
    [candidate_returns, portfolio_returns],
    axis=1,
    join="inner"
)
comparison.columns = ["Mon portefeuille", "Sanofi"]

comparison.head()

            Mon portefeuille    Sanofi
Date
2021-12-27          0.008081  0.012881
2021-12-28          0.003500  0.007001
2021-12-29         -0.000900 -0.011314
2021-12-30          0.003716  0.005858
2021-12-31         -0.006171  0.000386

In [53]:
comparison.shape

(1205, 2)

In [54]:
correlation_de_Pearson = comparison["Mon portefeuille"].corr(
    comparison["Sanofi"],
    method="pearson"
)
correlation_de_Pearson

np.float64(0.07471974710032216)

In [65]:
candidates_113 = [
    # Les 100 nouvelles
    "OR.PA",
    "MC.PA",
    "RMS.PA",
    "BNP.PA",
    "CS.PA",
    "CDI.PA",
    "EL.PA",
    "DG.PA",
    "BN.PA",
    "LR.PA",
    "SGO.PA",
    "KER.PA",
    "DSY.PA",
    "PUB.PA",
    "VIE.PA",
    "ML.PA",
    "AM.PA",
    "CAP.PA",
    "AMUN.PA",
    "EN.PA",
    "RI.PA",
    "URW.PA",
    "IPN.PA",
    "ERF.PA",
    "BVI.PA",
    "CA.PA",
    "ADP.PA",
    "LI.PA",
    "AC.PA",
    "RXL.PA",
    "BOL.PA",
    "FGR.PA",
    "GET.PA",
    "BIM.PA",
    "SW.PA",
    "AYV.PA",
    "ABVX.PA",
    "SPIE.PA",
    "ALO.PA",
    "EDEN.PA",
    "SCR.PA",
    "NEX.PA",
    "ODET.PA",
    "COV.PA",
    "DEC.PA",
    "ELIS.PA",
    "GFC.PA",
    "SOI.PA",
    "AKE.PA",
    "FDJU.PA",
    "TEP.PA",
    "LOUP.PA",
    "RUI.PA",
    "FR.PA",
    "MF.PA",
    "SOP.PA",
    "SK.PA",
    "CAF.PA",
    "AF.PA",
    "RF.PA",
    "FII.PA",
    "TRI.PA",
    "TKO.PA",
    "EXENS.PA",
    "BB.PA",
    "VCT.PA",
    "VIRP.PA",
    "MMB.PA",
    "ITP.PA",
    "ATE.PA",
    "ARTO.PA",
    "COFA.PA",
    "VRLA.PA",
    "OVH.PA",
    "RCO.PA",
    "FMONC.PA",
    "PLX.PA",
    "CARM.PA",
    "IDL.PA",
    "ALTA.PA",
    "EMEIS.PA",
    "NK.PA",
    "ARG.PA",
    "FRVIA.PA",
    "OPM.PA",
    "CBE.PA",
    "STF.PA",
    "VIV.PA",
    "MMT.PA",
    "IPS.PA",
    "DBG.PA",
    "TFI.PA",
    "CLARI.PA",
    "ANTIN.PA",
    "PEUG.PA",
    "ICAD.PA",
    "ERA.PA",
    "LSS.PA",
    "GLO.PA",
    "WLN.PA",
    "MEDCL.PA",
    "UBI.PA",
    "WAVE.PA",
    "74SW.PA",
    "BSD.PA",

    # Les 13 déjà testées
    "NAE.PA",
    "ATO.PA",
    "DBV.PA",
    "VK.PA",
    "NANO.PA",
    "GTT.PA",
    "BAIN.PA",
    "SU.PA",
    "AI.PA",
    "AIR.PA",
    "ORA.PA",
    "SAF.PA",
    "GLE.PA",
]

In [71]:
candidates2 = yf.download(
    candidates_113,
    start="2021-12-24",
    end="2026-09-15",
    auto_adjust = True
)["Close"]
candidates2.head

[*********************100%***********************]  118 of 118 completed

<bound method NDFrame.head of Ticker        74SW.PA     ABVX.PA      AC.PA      ADP.PA      AF.PA  \
Date
2021-12-24  25.329430   27.799999  25.071440  100.575096  19.881388
2021-12-27  25.618359   27.799999  25.302267   99.591263  19.841040
2021-12-28  26.196217   27.950001  25.240122  100.127899  19.866257
2021-12-29  26.196217   28.650000  25.124706  100.172615  19.619125
2021-12-30  26.003595   28.650000  25.373291  100.262054  19.548517
...               ...         ...        ...         ...        ...
2026-09-08  38.299999  101.000000  47.000000  111.500000  11.780000
2026-09-09  37.799999  101.199997  46.310001  108.800003  11.585000
2026-09-10  37.700001  100.300003  45.799999  108.300003  11.585000
2026-09-11  38.000000  101.300003  46.070000  108.900002  11.635000
2026-09-14  39.000000   99.650002  45.730000  108.900002  11.420000

Ticker           AI.PA      AIR.PA      AKE.PA     ALO.PA     ALTA.PA  ...  \
Date                                                                   ...
2021-12-24  103.053802  102.459152   96.988480  29.997936  109.142662  ...
2021-12-27  104.368690  103.064651   97.911797  30.537823  109.415512  ...
2021-12-28  105.108307  104.055489   98.835121  30.635981  111.052673  ...
2021-12-29  104.601517  102.862823   99.838722  30.145178  110.643364  ...
2021-12-30  105.245270  103.376579  100.159882  30.596718  111.871239  ...
...                ...         ...         ...        ...         ...  ...
2026-09-08  173.160004  200.699997   59.250000  16.320000   88.000000  ...
2026-09-09  168.320007  196.339996   58.049999  15.850000   85.199997  ...
2026-09-10  166.779999  195.779999   58.299999  15.500000   83.699997  ...
2026-09-11  166.520004  199.399994   57.000000  15.875000   84.500000  ...
2026-09-14  166.880005  195.000000   56.950001  15.780000   84.900002  ...

Ticker         UBI.PA     URW.PA     VCT.PA     VIE.PA     VIRP.PA     VIV.PA  \
Date
2021-12-24  43.340000        NaN  27.818901  25.703442  406.833221  10.904497
2021-12-27  42.959999        NaN  28.053991  25.598495  415.645477  10.858871
2021-12-28  42.730000        NaN  28.093174  26.300821  416.135101  10.899935
2021-12-29  42.200001        NaN  28.602531  26.026352  422.989044  10.913623
2021-12-30  42.919998        NaN  28.641714  25.897188  421.030792  10.904497
...               ...        ...        ...        ...         ...        ...
2026-09-08   4.895000  94.820000  65.099998  31.950001  316.000000   1.488000
2026-09-09   4.879000  93.839996  63.500000  31.559999  308.000000   1.481000
2026-09-10   4.875000  93.019997  62.099998  31.440001  302.000000   1.456000
2026-09-11   5.220000  92.900002  61.900002  31.440001  311.500000   1.528000
2026-09-14   5.320000  92.459999  60.500000  31.350000  314.500000   1.550000

Ticker          VK.PA    VRLA.PA    WAVE.PA      WLN.PA
Date
2021-12-24   7.869946  23.708101  49.945221  510.138641
2021-12-27   7.942816  23.817142  49.179779  503.990509
2021-12-28   8.102220  23.785988  49.945221  506.987091
2021-12-29   7.942816  24.190987  50.519302  499.857330
2021-12-30   7.874501  24.440216  51.284740  504.662170
...               ...        ...        ...         ...
2026-09-08  19.100000  19.100000  31.100000   14.198000
2026-09-09  19.174999  18.959999  30.049999   13.600000
2026-09-10  18.620001  18.719999  29.500000   13.950000
2026-09-11  18.535000  18.559999  30.150000   13.434000
2026-09-14  18.260000  18.440001  30.500000   13.848000

[1208 rows x 118 columns]>

In [74]:
returns_candidates_113 = candidates2.pct_change(fill_method=None).dropna()
returns_candidates_113.head()

Ticker,74SW.PA,ABVX.PA,AC.PA,ADP.PA,AF.PA,AI.PA,AIR.PA,AKE.PA,ALO.PA,ALTA.PA,...,UBI.PA,URW.PA,VCT.PA,VIE.PA,VIRP.PA,VIV.PA,VK.PA,VRLA.PA,WAVE.PA,WLN.PA
Date,,,,,,,,,,,,,,,,,,,,,
2024-06-10,0.000000,0.007752,-0.003337,-0.040507,-0.018182,-0.012537,-0.003600,-0.005025,-0.000848,-0.014706,...,-0.006443,-0.010834,-0.016238,-0.017453,-0.005510,-0.009865,0.006231,-0.009504,-0.034226,-0.031713
2024-06-11,0.008000,0.006154,-0.006181,-0.019560,-0.020468,-0.013205,-0.006423,0.000561,-0.050325,-0.075605,...,-0.039775,-0.041009,-0.009629,-0.024671,-0.020776,-0.009963,-0.024458,-0.004264,-0.033898,-0.023820
2024-06-12,-0.007937,0.001529,0.016066,0.002494,0.027861,0.020012,0.005791,-0.003926,-0.000893,-0.032715,...,-0.009905,0.015405,0.005556,0.007757,-0.001414,0.012323,-0.005712,0.017131,0.011164,0.002614
2024-06-13,0.008000,-0.016794,-0.021678,-0.018242,-0.028558,-0.035102,-0.023835,-0.030968,-0.044398,-0.007892,...,-0.007731,-0.010986,-0.006906,-0.020080,-0.028329,-0.005681,-0.038621,-0.024210,-0.042587,-0.058236
2024-06-14,-0.007937,-0.080745,-0.034672,-0.047297,-0.034180,-0.024498,-0.013580,-0.027310,-0.033053,-0.038636,...,-0.020165,-0.041259,-0.037552,-0.046448,-0.010204,-0.030810,-0.038845,-0.018878,-0.023064,-0.044762

In [75]:
comparison = pd.concat(
    [portfolio_returns, returns_candidates_113 ],
    axis=1,
    join="inner"
)
comparison.columns = [
    "Mon portefeuille", 
    "OR.PA",
    "MC.PA",
    "RMS.PA",
    "BNP.PA",
    "CS.PA",
    "CDI.PA",
    "EL.PA",
    "DG.PA",
    "BN.PA",
    "LR.PA",
    "SGO.PA",
    "KER.PA",
    "DSY.PA",
    "PUB.PA",
    "VIE.PA",
    "ML.PA",
    "AM.PA",
    "CAP.PA",
    "AMUN.PA",
    "EN.PA",
    "RI.PA",
    "URW.PA",
    "IPN.PA",
    "ERF.PA",
    "BVI.PA",
    "CA.PA",
    "ADP.PA",
    "LI.PA",
    "AC.PA",
    "RXL.PA",
    "BOL.PA",
    "FGR.PA",
    "GET.PA",
    "BIM.PA",
    "SW.PA",
    "AYV.PA",
    "ABVX.PA",
    "SPIE.PA",
    "ALO.PA",
    "EDEN.PA",
    "SCR.PA",
    "NEX.PA",
    "ODET.PA",
    "COV.PA",
    "DEC.PA",
    "ELIS.PA",
    "GFC.PA",
    "SOI.PA",
    "AKE.PA",
    "FDJU.PA",
    "TEP.PA",
    "LOUP.PA",
    "RUI.PA",
    "FR.PA",
    "MF.PA",
    "SOP.PA",
    "SK.PA",
    "CAF.PA",
    "AF.PA",
    "RF.PA",
    "FII.PA",
    "TRI.PA",
    "TKO.PA",
    "EXENS.PA",
    "BB.PA",
    "VCT.PA",
    "VIRP.PA",
    "MMB.PA",
    "ITP.PA",
    "ATE.PA",
    "ARTO.PA",
    "COFA.PA",
    "VRLA.PA",
    "OVH.PA",
    "RCO.PA",
    "FMONC.PA",
    "PLX.PA",
    "CARM.PA",
    "IDL.PA",
    "ALTA.PA",
    "EMEIS.PA",
    "NK.PA",
    "ARG.PA",
    "FRVIA.PA",
    "OPM.PA",
    "CBE.PA",
    "STF.PA",
    "VIV.PA",
    "MMT.PA",
    "IPS.PA",
    "DBG.PA",
    "TFI.PA",
    "CLARI.PA",
    "ANTIN.PA",
    "PEUG.PA",
    "ICAD.PA",
    "ERA.PA",
    "LSS.PA",
    "GLO.PA",
    "WLN.PA",
    "MEDCL.PA",
    "UBI.PA",
    "WAVE.PA",
    "74SW.PA",
    "BSD.PA",

    # Les 13 déjà testées
    "NAE.PA",
    "ATO.PA",
    "DBV.PA",
    "VK.PA",
    "NANO.PA",
    "GTT.PA",
    "BAIN.PA",
    "SU.PA",
    "AI.PA",
    "AIR.PA",
    "ORA.PA",
    "SAF.PA",
    "GLE.PA",
]
comparison.head()

,Mon portefeuille,OR.PA,MC.PA,RMS.PA,BNP.PA,CS.PA,CDI.PA,EL.PA,DG.PA,BN.PA,...,VK.PA,NANO.PA,GTT.PA,BAIN.PA,SU.PA,AI.PA,AIR.PA,ORA.PA,SAF.PA,GLE.PA
Date,,,,,,,,,,,,,,,,,,,,,
2024-06-10,-0.011534,0.000000,0.007752,-0.003337,-0.040507,-0.018182,-0.012537,-0.003600,-0.005025,-0.000848,...,-0.006443,-0.010834,-0.016238,-0.017453,-0.005510,-0.009865,0.006231,-0.009504,-0.034226,-0.031713
2024-06-11,-0.007235,0.008000,0.006154,-0.006181,-0.019560,-0.020468,-0.013205,-0.006423,0.000561,-0.050325,...,-0.039775,-0.041009,-0.009629,-0.024671,-0.020776,-0.009963,-0.024458,-0.004264,-0.033898,-0.023820
2024-06-12,0.016047,-0.007937,0.001529,0.016066,0.002494,0.027861,0.020012,0.005791,-0.003926,-0.000893,...,-0.009905,0.015405,0.005556,0.007757,-0.001414,0.012323,-0.005712,0.017131,0.011164,0.002614
2024-06-13,-0.023052,0.008000,-0.016794,-0.021678,-0.018242,-0.028558,-0.035102,-0.023835,-0.030968,-0.044398,...,-0.007731,-0.010986,-0.006906,-0.020080,-0.028329,-0.005681,-0.038621,-0.024210,-0.042587,-0.058236
2024-06-14,-0.034701,-0.007937,-0.080745,-0.034672,-0.047297,-0.034180,-0.024498,-0.013580,-0.027310,-0.033053,...,-0.020165,-0.041259,-0.037552,-0.046448,-0.010204,-0.030810,-0.038845,-0.018878,-0.023064,-0.044762

In [76]:
comparison.shape

(576, 119)

In [88]:
correlation_de_Pearson2 = comparison[
    [
    "OR.PA",
    "MC.PA",
    "RMS.PA",
    "BNP.PA",
    "CS.PA",
    "CDI.PA",
    "EL.PA",
    "DG.PA",
    "BN.PA",
    "LR.PA",
    "SGO.PA",
    "KER.PA",
    "DSY.PA",
    "PUB.PA",
    "VIE.PA",
    "ML.PA",
    "AM.PA",
    "CAP.PA",
    "AMUN.PA",
    "EN.PA",
    "RI.PA",
    "URW.PA",
    "IPN.PA",
    "ERF.PA",
    "BVI.PA",
    "CA.PA",
    "ADP.PA",
    "LI.PA",
    "AC.PA",
    "RXL.PA",
    "BOL.PA",
    "FGR.PA",
    "GET.PA",
    "BIM.PA",
    "SW.PA",
    "AYV.PA",
    "ABVX.PA",
    "SPIE.PA",
    "ALO.PA",
    "EDEN.PA",
    "SCR.PA",
    "NEX.PA",
    "ODET.PA",
    "COV.PA",
    "DEC.PA",
    "ELIS.PA",
    "GFC.PA",
    "SOI.PA",
    "AKE.PA",
    "FDJU.PA",
    "TEP.PA",
    "LOUP.PA",
    "RUI.PA",
    "FR.PA",
    "MF.PA",
    "SOP.PA",
    "SK.PA",
    "CAF.PA",
    "AF.PA",
    "RF.PA",
    "FII.PA",
    "TRI.PA",
    "TKO.PA",
    "EXENS.PA",
    "BB.PA",
    "VCT.PA",
    "VIRP.PA",
    "MMB.PA",
    "ITP.PA",
    "ATE.PA",
    "ARTO.PA",
    "COFA.PA",
    "VRLA.PA",
    "OVH.PA",
    "RCO.PA",
    "FMONC.PA",
    "PLX.PA",
    "CARM.PA",
    "IDL.PA",
    "ALTA.PA",
    "EMEIS.PA",
    "NK.PA",
    "ARG.PA",
    "FRVIA.PA",
    "OPM.PA",
    "CBE.PA",
    "STF.PA",
    "VIV.PA",
    "MMT.PA",
    "IPS.PA",
    "DBG.PA",
    "TFI.PA",
    "CLARI.PA",
    "ANTIN.PA",
    "PEUG.PA",
    "ICAD.PA",
    "ERA.PA",
    "LSS.PA",
    "GLO.PA",
    "WLN.PA",
    "MEDCL.PA",
    "UBI.PA",
    "WAVE.PA",
    "74SW.PA",
    "BSD.PA",

    # Les 13 déjà testées
    "NAE.PA",
    "ATO.PA",
    "DBV.PA",
    "VK.PA",
    "NANO.PA",
    "GTT.PA",
    "BAIN.PA",
    "SU.PA",
    "AI.PA",
    "AIR.PA",
    "ORA.PA",
    "SAF.PA",
    "GLE.PA",
 ]
].corrwith(
    comparison["Mon portefeuille"],
    method="pearson"
)

correlation_de_Pearson2

OR.PA     0.083162
MC.PA    -0.006048
RMS.PA    0.275711
BNP.PA    0.148832
CS.PA     0.170116
            ...
AI.PA     0.054214
AIR.PA    0.374410
ORA.PA    0.229342
SAF.PA    0.182965
GLE.PA    0.193487
Length: 118, dtype: float64

In [97]:
top_10 = correlation_de_Pearson2.nlargest(10)
bottom_10 = correlation_de_Pearson2.nsmallest(10)

print(f"voici le top 10: {top_10}")
print("--------------------------------------")
print(f"voici le bottom 10: {bottom_10}")

voici le top 10: WAVE.PA     0.510605
ANTIN.PA    0.470796
ITP.PA      0.451006
GLO.PA      0.404312
KER.PA      0.391948
IPS.PA      0.390245
MF.PA       0.376207
GFC.PA      0.375060
AIR.PA      0.374410
CBE.PA      0.374397
dtype: float64
--------------------------------------
voici le bottom 10: URW.PA     -0.132352
FRVIA.PA   -0.055804
RI.PA      -0.050728
AM.PA      -0.014237
MC.PA      -0.006048
VIE.PA     -0.002662
ADP.PA      0.053539
AI.PA       0.054214
VIRP.PA     0.064225
DBG.PA      0.080547
dtype: float64

In [101]:
correlation_20 = pd.concat([top_10, bottom_10])
correlation_20

WAVE.PA     0.510605
ANTIN.PA    0.470796
ITP.PA      0.451006
GLO.PA      0.404312
KER.PA      0.391948
IPS.PA      0.390245
MF.PA       0.376207
GFC.PA      0.375060
AIR.PA      0.374410
CBE.PA      0.374397
URW.PA     -0.132352
FRVIA.PA   -0.055804
RI.PA      -0.050728
AM.PA      -0.014237
MC.PA      -0.006048
VIE.PA     -0.002662
ADP.PA      0.053539
AI.PA       0.054214
VIRP.PA     0.064225
DBG.PA      0.080547
dtype: float64

In [102]:
tickers_20 = correlation_20.index.tolist()

In [108]:
prices_20 = yf.download(
    tickers_20,
    start="2021-12-24",
    end="2026-09-15",
    auto_adjust=True
)["Close"]
prices_20

[*********************100%***********************]  20 of 20 completed

Ticker,ADP.PA,AI.PA,AIR.PA,AM.PA,ANTIN.PA,CBE.PA,DBG.PA,FRVIA.PA,GFC.PA,GLO.PA,IPS.PA,ITP.PA,KER.PA,MC.PA,MF.PA,RI.PA,URW.PA,VIE.PA,VIRP.PA,WAVE.PA
Date,,,,,,,,,,,,,,,,,,,,
2021-12-24,100.575096,103.053810,102.459152,87.019409,26.827646,916.000000,8.257897,35.943520,89.491943,15.780992,33.732346,40.234291,600.915344,653.961121,84.296158,176.195236,NaN,25.703442,406.833221,49.945221
2021-12-27,99.591255,104.368675,103.064651,86.789085,27.193190,916.000000,8.515156,36.180332,89.934959,15.055632,33.690647,40.461281,611.411743,662.074036,85.491272,175.777908,NaN,25.598495,415.645538,49.179779
2021-12-28,100.127899,105.108315,104.055489,87.157616,26.938902,916.000000,8.480854,36.311901,90.414909,15.020248,33.857433,40.574780,612.811218,666.176147,84.614845,176.111771,NaN,26.300821,416.135071,49.945221
2021-12-29,100.172615,104.601524,102.862823,86.881218,26.875328,916.000000,8.562318,35.680386,90.304153,14.878714,34.149315,41.085506,615.347778,663.532654,84.455505,176.779510,NaN,26.026352,422.989044,50.519302
2021-12-30,100.262054,105.245270,103.376579,87.157616,27.463375,916.000000,8.558030,36.118938,90.931778,15.214856,34.649666,41.709736,619.108948,665.446960,84.614845,176.946426,NaN,25.897188,421.030762,51.284740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-08,111.500000,173.160004,200.699997,281.399994,8.420000,676.000000,9.215000,9.880000,67.449997,27.350000,36.060001,28.000000,244.399994,426.549988,86.150002,60.720001,94.820000,31.950001,316.000000,31.100000
2026-09-09,108.800003,168.320007,196.339996,278.799988,8.300000,672.000000,9.435000,9.520000,66.349998,26.600000,35.340000,28.160000,232.250000,411.250000,85.199997,60.040001,93.839996,31.559999,308.000000,30.049999
2026-09-10,108.300003,166.779999,195.779999,279.600006,8.160000,669.000000,9.370000,9.732000,65.750000,26.450001,35.900002,27.700001,234.149994,406.500000,83.750000,59.500000,93.019997,31.440001,302.000000,29.500000
2026-09-11,108.900002,166.520004,199.399994,278.799988,8.000000,669.000000,9.285000,9.590000,65.949997,26.400000,35.340000,28.260000,238.600006,415.299988,83.300003,59.419998,92.900002,31.440001,311.500000,30.150000
2026-09-14,108.900002,166.880005,195.000000,283.200012,7.980000,658.099976,9.385000,9.388000,65.699997,26.850000,36.080002,28.760000,238.000000,417.450012,83.050003,61.200001,92.459999,31.350000,314.500000,30.500000

In [111]:
prices_20.isna().sum()

Ticker
ADP.PA        0
AI.PA         0
AIR.PA        0
AM.PA         0
ANTIN.PA      0
CBE.PA        0
DBG.PA        0
FRVIA.PA      0
GFC.PA        0
GLO.PA        0
IPS.PA        0
ITP.PA        0
KER.PA        0
MC.PA         0
MF.PA         0
RI.PA         0
URW.PA      335
VIE.PA        0
VIRP.PA       0
WAVE.PA       0
dtype: int64

In [109]:
correlation_20 = candidates_returns1
returns_20 = candidates_returns1[tickers_20]

rendement_total = (1 + returns_20).prod() - 1

rendement_total

NameError: name 'candidates_returns1' is not defined